apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonfastapi
  labels:
    app: pythonfastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonfastapi
  template:
    metadata:
      labels:
        app: pythonfastapi
    spec:
      containers:
      - name: pythonfastapi-container
        image: murali90102/pythonfastapi:24
        env:
        - name: "APP_PORT"
          value: "8000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pythonfastapi
  labels:
    app: pythonfastapi
spec:
  selector:
    app: pythonfastapi

  type: NodePort
  ports:
  - nodePort: 31001
    port: 8000
    targetPort: 8000
